[package]
name = "test_elastio"
version = "0.1.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "weather"
path = "src/main.rs"

[dependencies]
assert_cmd = "2.0.7"
chrono = "0.4.23"
directories = "4.0.1"
dotenvs = "0.1.0"
log = "0.4.17"
logtest = "2.0.0"
openweathermap = "0.2.4"
serial_test = "0.9.0"
weer_api = "0.1.1"
